name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  http: ^1.1.0
  json_annotation: ^4.9.0
  xml: ^6.5.0

dependencies_override:
  logging: 1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  build_runner : ^2.4.9
  json_serializable: ^6.8.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
